import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Modular sidebar: group comarketer-app docs in a category
  tutorialSidebar: [
    {
      type: 'category',
      label: 'CoMarketer App',
      items: [
        'comarketer-app/overview',
        'comarketer-app/directory-structure',
        'comarketer-app/code-preview',
        'comarketer-app/main-logic-flow',
        'comarketer-app/deployment',
        'comarketer-app/api',
        'comarketer-app/components',
        'comarketer-app/architecture',
      ],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
